### ISSUE TITLE
Change gpt-3.5-turbo to text-embedding-ada-002 to generate embeds

### ISSUE THREAD

**Issue by darkanubis0100** [libraryofcelsus/Aetherius_AI_Assistant#12]
Why during embedding generation, is gpt-3.5-turbo used instead of text-embedding-ada-002?

I am seeing things like this in my billing panel:

> Local time: 8 jun 2023, 14:15
> gpt-3.5-turbo-0301, 63 requests
> 18,792 prompt + 4,115 completion = 22,907 tokens
> 
> Local time: 8 jun 2023, 14:15
> text-embedding-ada-002-v2, 4 requests
> 493 prompt + 0 completion = 493 tokens

That is definitely not normal, doing the embedding from GPT instead of Ada is a very high cost if you have to process up to 1M tokens as I usually have to do.

Reviewing the code, it has indeed been established that the embeddings are delegated to text-embedding-ada-002, but when it comes down to it, it is gpt-3.5 that is generating them.

**Comment by darkanubis0100** [comment]
> Local time: 8 jun 2023, 14:15
> gpt-3.5-turbo-0301, 63 requests
> 18,792 prompt + 4,115 completion = 22,907 tokens
> 
> Local time: 8 jun 2023, 14:15
> text-embedding-ada-002-v2, 4 requests
> 493 prompt + 0 completion = 493 tokens
> 
> Local time: 8 jun 2023, 14:20
> gpt-3.5-turbo-0301, 32 requests
> 8,624 prompt + 2,030 completion = 10,654 tokens
> 
> Local time: 8 jun 2023, 14:25
> gpt-3.5-turbo-0301, 100 requests
> 26,169 prompt + 5,541 completion = 31,710 tokens
> 
> Local time: 8 jun 2023, 14:25
> text-embedding-ada-002-v2, 3 requests
> 243 prompt + 0 completion = 243 tokens

Very little is using Ada

**Comment by darkanubis0100** [comment]
This is how the models should really be used for embedding:

> Local time: 8 jun 2023, 2:50
> gpt-3.5-turbo-0301, 1 request
> 55 prompt + 9 completion = 64 tokens
> 
> Local time: 8 jun 2023, 2:50
> text-embedding-ada-002-v2, 75 requests
> 21,991 prompt + 0 completion = 21,991 tokens
> 
> Local time: 8 jun 2023, 2:55
> text-embedding-ada-002-v2, 521 requests
> 149,767 prompt + 0 completion = 149,767 tokens
> 
> Local time: 8 jun 2023, 3:00
> text-embedding-ada-002-v2, 535 requests
> 154,043 prompt + 0 completion = 154,043 tokens
> 
> Local time: 8 jun 2023, 3:05
> text-embedding-ada-002-v2, 254 requests
> 85,398 prompt + 0 completion = 85,398 tokens

**Comment by libraryofcelsus** [comment]
It functions correctly to my knowledge, I think you have just misunderstood the purpose of the program.  Having everything done in embeddings removes the ability to dynamically search the multiple dbs and load them in varying correct orders.  Aetherius is a simulacrum of the human thought process/memory retrieval and doesn't function like other chatbots. The high usage of gpt-3.5 is from loading the various types of memories, not from it being embedded.  The embeddings are only used for the database upsert.

**Comment by libraryofcelsus** [comment]
> Why during embedding generation, is gpt-3.5-turbo used instead of text-embedding-ada-002?
> 
> I am seeing things like this in my billing panel:
> 
> > Local time: 8 jun 2023, 14:15
> > gpt-3.5-turbo-0301, 63 requests
> > 18,792 prompt + 4,115 completion = 22,907 tokens
> > Local time: 8 jun 2023, 14:15
> > text-embedding-ada-002-v2, 4 requests
> > 493 prompt + 0 completion = 493 tokens
> 
> That is definitely not normal, doing the embedding from GPT instead of Ada is a very high cost if you have to process up to 1M tokens as I usually have to do.
> 
> Reviewing the code, it has indeed been established that the embeddings are delegated to text-embedding-ada-002, but when it comes down to it, it is gpt-3.5 that is generating them.

It functions correctly to my knowledge, I think you have just misunderstood the purpose of the program. Having everything done in embeddings removes the ability to dynamically search the multiple dbs and load them in varying correct orders. Aetherius is a simulacrum of the human thought process/memory retrieval and doesn't function like other chatbots. The high usage of gpt-3.5 is from loading the various types of memories, not from it being embedded. The embeddings are only used for the database upsert.

**Comment by darkanubis0100** [comment]
I am now understanding you then, it is not like the typical ChatPDF that you pass documentation to and it remains in the DB

**Comment by darkanubis0100** [comment]
I am now understanding you then, it is not like the typical ChatPDF that you pass documentation to and it remains in the DB
